logging:
  level:
    root: DEBUG
    com.road.to.payments.service.impl: DEBUG

spring:
  docker:
    compose:
      enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

  datasource:
    url: jdbc:postgresql://localhost:5433/payments   # URL ??????????? ? ??????????
    username: postgres                               # USER ?? docker-compose
    password: postgres                           # PASSWORD ?? docker-compose
#  jpa:
#    hibernate:
#      ddl-auto: update    # ??? validate / none / create-drop
#    show-sql: true        # ????? SQL ? ??????? (?? ???????)
#    properties:
#      hibernate:
#        format_sql: true
  sql:
    init:
      mode: always

job:
  count-balances-by-type-and-date:
    cron: "*/30 * * * * *"
